blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/asbjborg/journal-addon/issues/new?template=feature_request.md
    about: Request a new feature
  - name: Bug Report
    url: https://github.com/asbjborg/journal-addon/issues/new?template=bug_report.md
    about: Report a bug
